# f=open('n1.txt','x')
# print(f.name)
# print(f.mode)
# print(f.encoding)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# --------------------------------

# f=open('n2.txt','x+')
# print(f.name)
# print(f.mode)
# print(f.encoding)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# -----------------------

# f=open('n2.txt','x+')
# print(f.name)
# print(f.mode)
# print(f.encodfing)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# -------------------------------

# f=open('n3.txt','w+')
# print(f.name)
# print(f.mode)
# print(f.encoding)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# --------------------------

# f=open('n1.txt','a')
# data=('Hello\n')
# f.writelines(data)
# # f.readable()
# f1=open('n1.txt','r')
# data=f1.readlines()
# print(data)
# f.close()

f=open('n1.txt','a+')
data=('Hello\n')
f.writelines(data)
print(f.tell())
print(f.read())
f.seek(0)
print(f.tell())
print(f.read())
data=f.readlines()
print(data)
f.close()